# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-08 16:42
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=10, unique=True)),
                ('point', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('img', models.ImageField(blank=True, null=True, upload_to='accounts/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
